name: test_release
on:
  push: {tags:  ['v*'] } # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build_release:
    runs-on: windows-latest # default batch, powershell
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with: {dotnet-version: 3.1.301}
    - name: Install dependencies
      run: cd LucaSystemTools/LucaSystemTools && dotnet restore
    - name: Build
      run: cd LucaSystemTools/LucaSystemTools && dotnet build --configuration Release --no-restore
    - name: rename
      run : ren LucaSystemTools/LucaSystemTools/bin/Release/netcoreapp3.1/ LucaSystemTool
    - name: 7zip release
      run : 7z a -t7z -mx=9 LucaSystemTool_release.7z ./LucaSystemTools/LucaSystemTools/bin/Release/LucaSystemTool # must have ., or zip the whole path
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "LucaSystemTool_release.7z"
        bodyFile: ""
        token: ${{ secrets.GITHUB_TOKEN }}
